# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64

name: drone-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - lightning=2.6.0
  - pip
  - pip:
      - stable-baselines3
      - gym
      - pybullet
      - ray[rllib]
