# This file may be used to create an environment using:
# $ conda env create -f <file.yml>
# $ conda activate drone-env
# platform: osx-arm64

name: drone-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip

  # PyTorch (Apple Silicon / MPS)
  - pytorch=2.5.*
  - torchvision
  - torchaudio
  - lightning=2.6.*
  - pybullet
  - ffmpeg

  # Python packages via pip
  - pip:
      - gym==0.26.*
      - stable-baselines3
      - ray[rllib]==2.9.*
      - hydra-core
      - pillow
      - numpy
      - matplotlib
      - Pillow
      - cycler
      - tensorboard
      - wandb
      - optuna
