name: pytorch-ppo-research
channels:
  - conda-forge
dependencies:
  - aom=3.5.0=h7ea286d_0
  - box2d-py=2.3.8=py310h0f1eb42_7
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - cairo=1.16.0=h73a0509_1014
  - cffi=1.15.1=py310h2399d43_2
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=4.4.2=gpl_hf4c414c_110
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hd633e50_1
  - future=0.18.2=pyhd8ed1ab_6
  - gettext=0.21.1=h0186832_0
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.13=h9f76cd9_1001
  - gym=0.21.0=py310hbe9552e_2
  - gym-all=0.21.0=py310hb6292c7_2
  - gym-box2d=0.21.0=py310hb6292c7_2
  - gym-classic_control=0.21.0=py310hb6292c7_2
  - gym-other=0.21.0=py310hb6292c7_2
  - gym-toy_text=0.21.0=py310hb6292c7_2
  - harfbuzz=5.3.0=hddbc195_0
  - hdf5=1.12.2=nompi_h33dac16_100
  - icu=70.1=h6b3803e_0
  - jasper=2.0.33=hba35424_0
  - jpeg=9e=he4db4b2_2
  - krb5=1.19.3=he492e65_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.86.0=h1c293e1_1
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_26
  - libgfortran5=11.3.0=hdaf2cc0_26
  - libglib=2.74.1=h4646484_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.47.0=h519802c_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.6.0=py310hb63fde9_4
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.9=hb5ab8b9_0
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.4.0=hfa0b094_4
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.5=h7cfbb63_0
  - lz4=4.0.2=py310ha6df754_0
  - lz4-c=1.9.3=hbdafb3b_1
  - ncurses=6.3=h07bb92c_1
  - nettle=3.8.1=h63371fa_1
  - ninja=1.11.0=hf86a087_0
  - numpy=1.23.5=py310h5d7c261_0
  - opencv=4.6.0=py310hb6292c7_4
  - openh264=2.3.1=hb7217d7_1
  - openssl=3.0.7=h03a7124_0
  - p11-kit=0.24.1=h29577a5_0
  - pcre2=10.40=hb34f9b4_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - py-opencv=4.6.0=py310h69fb684_4
  - pycparser=2.21=pyhd8ed1ab_0
  - pyglet=1.5.27=py310hbe9552e_1
  - python=3.10.8=h3ba56d0_0_cpython
  - python_abi=3.10=3_cp310
  - pytorch=1.12.1=cpu_py310h7410233_1
  - readline=8.1.2=h46ed386_0
  - scipy=1.9.3=py310ha0d8a01_2
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sleef=3.5.1=h156473d_2
  - svt-av1=1.3.0=h7ea286d_0
  - tk=8.6.12=he1e0b03_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022f=h191b570_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.2.6=h57fd34a_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
      - absl-py==1.3.0
      - cachetools==5.2.0
      - certifi==2022.9.24
      - charset-normalizer==2.1.1
      - click==8.1.3
      - docker-pycreds==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.29
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - idna==3.4
      - markdown==3.4.1
      - markupsafe==2.1.1
      - oauthlib==3.2.2
      - pandas==1.5.2
      - pathtools==0.1.2
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - python-dateutil==2.8.2
      - pytz==2022.6
      - pyyaml==6.0
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sentry-sdk==1.11.1
      - setproctitle==1.3.2
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.0
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torch-tb-profiler==0.4.0
      - urllib3==1.26.13
      - wandb==0.13.6
      - werkzeug==2.2.2
prefix: /Users/janinaalicamattes/miniforge3/envs/pytorch-ppo-research
